---
title: "ETOC: Permutation Study"
output:
  html_document:
    toc: true
    theme: united
---


# Non-Parametric Permutation Study

## Permutation Study

```{r Setup}
set.seed(123)
library(dplyr)
library(MASS)
library(ggplot2)
library(tidyr)
library(edgeR)
library(limma)

### Load Helper Functions
sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))

### Load Data
dataDir <- "../data/"
tcgaData <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))

### Subset Data for two-group Comparison
tcgaDataCleaned <- tcgaData <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))
tcgaDataCleaned$counts <- tcgaData$counts[,!tcgaData$patientMaskDelete]
tcgaDataCleaned$group  <- tcgaData$group[!tcgaData$patientMaskDelete]

### Load p-values of all methods and convert to data frame
namesList <- names(tcgaData$Results)
LIHCRes <- as.data.frame(tcgaData$Results)
colnames(LIHCRes) <- namesList

### Compute Rejected Genes and print number of Rejections for all Methods
LIHCResDE <- LIHCRes <= 0.01
colSums(LIHCResDE, na.rm = T)

### Rename Genes to Integers
rownames(tcgaDataCleaned$counts) <- 1:nrow(tcgaDataCleaned$counts)

### Load previous simulation results or create new list
resFileName <- paste0(dataDir, "LIHCGenerationResults.Rds")
if (file.exists(resFileName)){
  permResults <- readRDS(resFileName)
} else{
  permResults <- list()
}
```


# Generation: Equal Distributions

```{r}
### Loading Data an Helper Functions
. <- sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))
glm.nb <- MASS::glm.nb
dataDir <- "../data/"

resFileName <- paste0(dataDir, "LIHCGenerationResults.Rds")
tcgaData   <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))

DeSize <- 200
pGenes <- DeSize*6

### Get Parameters for Simulation
randInt <- sample(nrow(tcgaData$counts), 10000)
d <- edgeR::DGEList(counts = tcgaData$counts[randInt,])
rownames(d) <-  1:nrow(d)
d <- edgeR::calcNormFactors(d)
d <- edgeR::estimateDisp(d)
phi <- d$tagwise.dispersion
mu <- rowMeans(d$counts*d$samples$norm.factors)
mu_1 <- mu_2 <-  mu[mu > 0.1][1:pGenes]
phi_1 <- phi_2 <- phi[mu > 0.1][1:pGenes]

### Create differential expression
mu_2[1:(DeSize/2)] <- mu_2[1:(DeSize/2)]*3
mu_2[((DeSize/2)+1):DeSize] <- mu_2[((DeSize/2)+1):DeSize]/3

### Initiate
genResults <-list()
genResults$plot_data <- data.frame(mu_1 = mu_1,
                        mu_2 = mu_2,
                        phi_1 = phi_1,
                        phi_2 = phi_2,
                        de_mask = 1:pGenes <= DeSize)

nList <- list("12" = 12, "60" = 60, "120" = 120)
nRepl <- 100 #ca. 17:00
```


```{r}
t0 <- Sys.time()
  ### For Each Sample Size n:
  genResults$geneData$noCovariates <- lapply(nList, function(n){
  print(n)
  c <- 0
  tN <- Sys.time()
  ### Inner Loop: Replicate n_repl times
  replicate(nRepl,{
    PrintProgress(c, nRepl, tN)
    XYData <- SimulateNB(n, pGenes, mu1 = mu_1, mu2 = mu_2, phi1 = phi_1, phi2 = phi_1,
                         beta = rep(0, pGenes), 
                         offset = sample(d$samples$norm.factors, n))
    res    <- RunAllMethods(XYData$Y, XYData$X)
    c <<- c + 1
    return(res)
    })
  })


saveRDS(genResults, file = resFileName)
print(Sys.time() - t0)
rm(mu_1, mu_2, phi_1, phi_2)
```

## Plotting

```{r}
library(ggplot2)
library(dplyr)
data.dir <- "../data/"
resFileName <- paste0(data.dir, "LIHCGenerationResults.Rds")
genResults <- readRDS( file = resFileName)
t1_data <- GetT1Data(PlotData = genResults$plot_data,
                     GeneData = genResults$geneData$noCovariates, 
                     alphas = rep(0.01, 12))
```




```{r}
labelOrder <- row.names(genResults$geneData$noCovariates$"12")
title_name <- "Probability of Rejection under H0"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~factor(n, levels = c(12, 60, 120))) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  geom_hline(yintercept = 0.01) +
  scale_y_continuous(trans = "sqrt", expand = c(0,0), breaks = c(0, 0.01, 0.05, 0.1, 0.2, 0.4), limits = c(0, 0.4))

file_name <- paste("../plots/GenH0", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1, width = 4, height = 3.5)
p1
```


```{r}

title_name <- "Probability of Rejection under HA"
p1 <- t1_data %>%
  dplyr::filter(de_mask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~factor(n, levels = c(12, 60, 120), labels = c("n = 12", "n = 60", "n = 120"))) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  scale_y_continuous(trans = "sqrt", expand = c(0,0), breaks = c(0, 0.01, 0.05, 0.1, 0.2,  0.4, 0.8, 1))

file_name <- paste("../plots/GenH0", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1, width = 4, height = 3.5)
p1
```
# Covariates

```{r}
### Loading Data an Helper Functions
. <- sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))
glm.nb <- MASS::glm.nb
dataDir <- "../data/"

resFileName <- paste0(dataDir, "LIHCGenerationResults.Rds")
tcgaData   <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))

DeSize <- 200
pGenes <- DeSize*6

### Get Parameters for Simulation
randInt <- sample(nrow(tcgaData$counts), 5000)
d <- edgeR::DGEList(counts = tcgaData$counts[randInt,])
rownames(d) <-  1:nrow(d)
d <- edgeR::calcNormFactors(d)
d <- edgeR::estimateDisp(d)
phi <- d$tagwise.dispersion
mu <- rowMeans(d$counts*d$samples$norm.factors)
mu_1 <- mu_2 <-  mu[mu > 0.1][1:pGenes]
phi_1 <- phi_2 <- phi[mu > 0.1][1:pGenes]

### Create differential expression
mu_2[1:(DeSize/2)] <- mu_2[1:(DeSize/2)]*2
mu_2[((DeSize/2)+1):DeSize] <- mu_2[((DeSize/2)+1):DeSize]/2

### Initiate
genResults <-list()
genResults$plot_data <- data.frame(mu_1 = mu_1,
                        mu_2 = mu_2,
                        phi_1 = phi_1,
                        phi_2 = phi_2,
                        de_mask = 1:pGenes <= DeSize)

nList <- list("12" = 12, "60" = 60, "120"= 120)
nRepl <- 100 #ca. 17:00
```




```{r}
edgeRPipelineCovariates <- function(XYData){
  d <- edgeR::DGEList(counts = XYData$Y, group = XYData$X$beta)
  design <- model.matrix(~XYData$X$gamma + as.factor(XYData$X$beta))
  d <- calcNormFactors(d)
  d <- edgeR::estimateDisp(d, design)
  fit <- edgeR::glmQLFit(d, design)
  qlf2vs1 <- glmQLFTest(fit, coef = 3)
  qlf2vs1$table$PValue
  
}
limmaPipelineCovariates <- function(XYData){
  dge <- edgeR::DGEList(counts=XYData$Y)
  design = model.matrix(~XYData$X$gamma + as.factor(XYData$X$beta))
  dge <- edgeR::calcNormFactors(dge)
  dge <- edgeR::estimateDisp(dge, design)
  # Normalization (TMM followed by voom)
  v   = limma::voom(dge, design, plot=FALSE)
  
  # Fit model to data given design
  fit = limma::lmFit(v, design)
  
  #extract p-values from moderated t-statistic
  fit = limma::eBayes(fit)
  fit$p.value[,3]
}
DESeq2PipelineCovariates <- function(XYData){
  X   <- data.frame("Sex" = as.factor(XYData$X$gamma),
                    "Treatment" = as.factor(XYData$X$beta))
  dds <- DESeq2::DESeqDataSetFromMatrix(XYData$Y,
                                        colData = X,
                                        design = ~ Sex + Treatment)
  dds <- DESeq2::DESeq(dds, quiet = T)
  DESeq2::results(dds)$pvalue
}
FlipScoresPipelineCovariates <- function(XYData, family = "poisson", scoreType = "standardized", nFlips = 40){
  pVals <- sapply(1:nrow(XYData$Y), function(i) {

    Yi <- XYData$Y[i,] #needed to avoid error in formula
    tryCatch(expr = {
      if(family == "negbinom"){
        mod0 <- flipscores::flipscores(Yi ~ XYData$X$gamma + XYData$X$beta,
                           family = "negbinom",
                           score_type = scoreType,
                           n_flips = nFlips, to_be_tested = 3)
      }
      else if(family == "poisson"){
        mod0 <- flipscores::flipscores(Yi ~ XYData$X$gamma + XYData$X$beta,
                           family = poisson,
                           score_type = scoreType,
                           n_flips = nFlips, to_be_tested = 3)
      }

      #extract p-value from summary
      coef(summary(mod0))[3, 5]
  },
    error = function(e) {
      return(NA)
    }
    )
  })
}

RunAllMethodsCovariates <- function(XYData){
  suppressMessages(suppressWarnings({
    res <- list()
    res$Limma    <- limmaPipelineCovariates(XYData)
    res$EdgeRQL  <- edgeRPipelineCovariates(XYData)
    res$DESeq2   <- DESeq2PipelineCovariates(XYData)
    res$FsPB     <- FlipScoresPipelineCovariates(XYData, "poisson", scoreType = "basic", nFlips = 400)
    res$FsPE     <- FlipScoresPipelineCovariates(XYData, "poisson", scoreType = "effective", nFlips = 400)
    res$FsPS     <- FlipScoresPipelineCovariates(XYData, "poisson", scoreType = "standardized", nFlips = 400)
    res$FsNBB     <- FlipScoresPipelineCovariates(XYData, "negbinom", scoreType = "basic", nFlips = 400)
    res$FsNBE     <- FlipScoresPipelineCovariates(XYData, "negbinom", scoreType = "effective", nFlips = 400)
    res$FsNBS     <- FlipScoresPipelineCovariates(XYData, "negbinom", scoreType = "standardized", nFlips = 400)
  }))
  return(res)
}
```





```{r}
genResults$geneData <- lapply(nList, function(n){
  c <- 0
  print(n)
  tN <- Sys.time()
  ### Inner Loop: Replicate n_repl times
  replicate(nRepl,{
    PrintProgress(c, nRepl, tN)
    XYData <- SimulateNB(n, pGenes, mu1 = mu_1, mu2 = mu_2, phi1 = phi_1, phi2 = phi_1, beta = rnorm(pGenes, 0, 0.2))
    res    <- RunAllMethodsCovariates(XYData)
    c <<- c + 1
    return(res)
    })
  })

resFileName <- paste0(dataDir, "LIHCGenerationResultsCov.Rds")
saveRDS(genResults, file = resFileName)
#system('shutdown -s')
```


```{r}
library(ggplot2)
library(dplyr)
labelOrder <- 
. <- sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))
data.dir <- "../data/"
resFileName <- paste0(data.dir, "LIHCGenerationResultsCov.Rds")
genResults <- readRDS( file = resFileName)
t1_data <- GetT1Data(PlotData = genResults$plot_data,
                     GeneData = genResults$geneData, 
                     alphas = rep(0.01, 12))



labelOrder <- row.names(genResults$geneData$"12")
title_name <- "Probability of Rejection under H0"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=20, size=1, color="red", fill="red") +
  facet_wrap(~factor(n, levels = c(12, 60, 120))) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  geom_hline(yintercept = 0.01) +
  scale_y_continuous(trans = "sqrt", expand = c(0,0), breaks = c(0, 0.01, 0.05, 0.1, 0.2,  0.4, 0.8, 1))

file_name <- paste("../plots/GenH0Covariates", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1, width = 4, height = 3.5)
p1
```
```{r}
labelOrder
```

```{r}
title_name <- "Probability of Rejection under HA"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~factor(n, levels = c(12, 60, 120))) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  scale_y_continuous(trans = "sqrt", expand = c(0,0), breaks = c(0, 0.01, 0.05, 0.1, 0.2,  0.4, 0.8, 1))

file_name <- paste("../plots/GenHACovariates", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1, width = 4, height = 3.5)
p1
```

