---
title: "ETOC: Permutation Study"
output:
  html_document:
    toc: true
    theme: united
---


# Permutation Study Unfiltered

```{r Setup}
set.seed(123)
library(dplyr)
library(MASS)
library(ggplot2)
library(tidyr)

### Load Helper Functions
sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))

### Load Data
dataDir <- "../data/"
tcgaData <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))

### Subset Data for two-group Comparison
tcgaDataCleaned <- tcgaData <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))
tcgaDataCleaned$counts <- tcgaData$counts[,!tcgaData$patientMaskDelete]
tcgaDataCleaned$group  <- tcgaData$group[!tcgaData$patientMaskDelete]

### Load p-values of all methods and convert to data frame
namesList <- names(tcgaData$Results)
LIHCRes <- as.data.frame(tcgaData$Results)
colnames(LIHCRes) <- namesList

### Compute Rejected Genes and print number of Rejections for all Methods
LIHCResDE <- LIHCRes <= 0.01
colSums(LIHCResDE, na.rm = T)

### Rename Genes to Integers
rownames(tcgaDataCleaned$counts) <- 1:nrow(tcgaDataCleaned$counts)

### Load previous simulation results or create new list
resFileName <- paste0(dataDir, "LIHCPermutationResults.Rds")
if (file.exists(resFileName)){
  permResults <- readRDS(resFileName)
} else{
  permResults <- list()
}
```


# Load 
```{r}
### Create Masks for Genes that are Differentially Expressed (De)  and
### Not Differentially Expressed (NDe)
De  <- LIHCRes <= 0.01
NDe <- LIHCRes > 0.1
De <- rowSums(De, na.rm = T) >= 7
NDe <- rowSums(NDe, na.rm = T) >= 5

### Get Random Selection of genes of a given size for a given ratio
DeSize <- 50
De  <- sample(which(De), DeSize)
NDe <- sample(which(NDe), DeSize*5)
YDe  <- tcgaDataCleaned$counts[De,]
YNDe <- tcgaDataCleaned$counts[NDe,]
YAll <- rbind(YDe, YNDe)
rownames(YAll) <- 1:nrow(YAll)
XAll <- tcgaDataCleaned$group == "Primary solid Tumor"   

### Compute norm factors and Dispersion on full dataset for later analyses
dAll <- edgeR::DGEList(counts = YAll, group = XAll)
dAll <- edgeR::calcNormFactors(dAll)
dAll <- edgeR::estimateDisp(dAll)

### Maximum Absolute Correlation for each gene
cAll <- abs(cor(t(edgeR::cpm(dAll))))
diag(cAll) <- 0
cMax <- apply(cAll, 2, max) 

### save plotting data
plotData <- data.frame(mu = rowMeans(dAll$counts * dAll$samples$norm.factors),
                        phi = dAll$tagwise.dispersion,
                        corrMax = cMax,
                        deMask = 1:nrow(dAll) <= DeSize)

rm(cMax, cAll)

### Set Simulation Parameters
nRepl <- 100
nList <- list("10" = 10,  "40" = 40)

permResults$plotData$unfiltered <- plotData
saveRDS(permResults, file = resFileName)

rm(plotData, tcgaData)
```



```{r}
### Helper Function to run all Methods
RunAllMethods <- function(Y, X){
  suppressMessages(suppressWarnings({
  res <- list()
  res$Limma    <- LimmaPipeline(Y, X)
  res$EdgeREt  <- EdgeRPipeline(Y, X, test = "exact")
  res$EdgeRQl  <- EdgeRPipeline(Y, X, test = "ql")
  res$DESeq2   <- DESeq2Pipeline(Y, X)
  res$MWU      <- MWUPipeline(Y, X)
  res$DP       <- DirectPermutationsPipeline(X, Y, nFlips = 100)
  res$FsPB     <- FlipScoresPipeline(Y, X, "poisson", scoreType = "basic", nFlips = 20)
  res$FsPE     <- FlipScoresPipeline(Y, X, "poisson", scoreType = "effective", nFlips = 20)
  res$FsPS     <- FlipScoresPipeline(Y, X, "poisson", scoreType = "standardized", nFlips = 20)
  }))
  return(res)
  
}
```



```{r Running Simulation w/o Filtering}
t0 <- Sys.time()    
### For Each Sample Size n:
permResults$geneData$unfiltered <- lapply(nList, function(n){
  print(n)
  c <- 0
  tN <- Sys.time()
  ### Inner Loop: Replicate n_repl times
  replicate(nRepl,{
    ### Print Progress and Increase Counter
    PrintProgress(c, nRepl, tN)
    c <<- c + 1
    XYData <- GetXYperm(n, YDe, YNDe, XAll, DESize, dAll$samples$norm.factors)
    res    <- RunAllMethods(XYData$Y, XYData$X)
  return(res)
  })
})

saveRDS(permResults, file = resFileName)
print(Sys.time() - t0)
```


```{r Prepare Data w. Filtering}
### Create Masks for Genes that are Differentially Expressed (De)  and
### Not Differentially Expressed (NDe)
De  <- LIHCRes <= 0.01
NDe <- LIHCRes > 0.1
De <- rowSums(De, na.rm = T) >= 7
NDe <- rowSums(NDe, na.rm = T) >= 5
### Get Random Selection of genes of a given size for a given ratio
DeSize <- 100
De  <- sample(which(De), DeSize)
NDe <- sample(which(NDe), DeSize*5)
YDe  <- tcgaDataCleaned$counts[De,]
YNDe <- tcgaDataCleaned$counts[NDe,]
YAll <- rbind(YDe, YNDe)
rownames(YAll) <- 1:nrow(YAll)
XAll <- tcgaDataCleaned$group == "Primary solid Tumor"   

### Compute norm factors and Dispersion on full dataset for later analyses
dAll <- edgeR::DGEList(counts = YAll, group = XAll)
dAll <- edgeR::calcNormFactors(dAll)
dAll <- edgeR::estimateDisp(dAll)

### Maximum Absolute Correlation for each gene
cAll <- abs(cor(t(edgeR::cpm(dAll))))
diag(cAll) <- 0
cMax <- apply(cAll, 2, max) 

### save plotting data
plotData <- data.frame(mu = rowMeans(dAll$counts * dAll$samples$norm.factors),
                        phi = dAll$tagwise.dispersion,
                        corrMax = cMax,
                        deMask = 1:nrow(dAll) <= DeSize)

rm(cMax, cAll)

### Set Simulation Parameters
nRepl <- 100
nList <- list("10" = 10,  "40" = 40)

### Load previous simulation results or create new list
resFileName <- paste0(dataDir, "LIHCPermutationResults.Rds")
if (file.exists(resFileName)){
  permResults <- readRDS(resFileName)
} else{
  permResults <- list()
}

permResults$plotData$filtered <- plotData
saveRDS(permResults, file = resFileName)
rm(plotData)
```


```{r Running Simulation w Filtering}
t0 <- Sys.time()   
### For Each Sample Size n:
permResults$geneData$filtered <- lapply(nList, function(n){
  print(n)
  c <- 0
  tN <- Sys.time()
  ### Inner Loop: Replicate n_repl times
  replicate(nRepl,{
    PrintProgress(c, nRepl, tN)
    c <<- c + 1
    XYData <- GetXYperm(n, YDe, YNDe, XAll, DESize, dAll$samples$norm.factors)
    rn <- rownames(XYData$Y)
    
    ### Filtering
    d <- edgeR::DGEList(counts = XYData$Y)
    d <- edgeR::calcNormFactors(d)
    keep = edgeR::filterByExpr(d)
    d <- d[keep,]
    XYData$Y <- d$counts
    
    res <- RunAllMethods(XYData$Y, XYData$X)
    
    df <- data.frame(row.names = rn, matrix(nrow = length(rn), ncol = 9))
    df[keep, ] <- as.data.frame(res)
    
    colnames(df) <- names(res)
    return(df)
    })
})

saveRDS(permResults, file = resFileName)
print(Sys.time() - t0)



```




## Create Plots

```{r}
dataDir <- "../data/"
tcgaData    <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))
resFileName <- paste0(dataDir, "LIHCPermutationResults.Rds")
permResults <- readRDS(resFileName)
```

```{r}
GetModels <- function(t1Data, formula, sp = c(0.25, 0.25, 0.25)){
  paramGrid <- expand.grid(Model = unique(t1Data$name),
                            n =  as.character(unique(t1Data$n)),
                            DE = c(T,F))
  fittedModels <- apply(paramGrid, 1, function(p){
    mask <- t1Data$n == p["n"] & t1Data$deMask == p["DE"] & t1Data$name == p["Model"]
    b1 <- mgcv::gam(formula, data = t1Data[mask,],
                    family = mgcv::betar(eps = 0.0001), sp = sp)
    
  })
  names(fittedModels) <- paste(paramGrid$Model, paramGrid$n, ifelse(paramGrid$DE, "DE", "NDE"), sep = "_")
  return(fittedModels)
}
```


```{r}
GetPreds <- function(models, cutoffs){
           
 newd <- data.frame(mu = seq(cutoffs$mu[1], cutoffs$mu[2], length.out = 200),
                    phi = seq(cutoffs$phi[1], cutoffs$phi[2], length.out = 200),
                    corrMax = seq(cutoffs$corrMax[1], cutoffs$corrMax[2],
                                   length.out = 200)
                    )
  
  margin.terms <- all.vars(models[[1]]$formula)[2:4]
  model.terms <- paste0("s(", all.vars(models[[1]]$formula)[2:4], ")")
  
  model.terms <- c("s(log(mu))", "s(phi)", "s(corrMax)")
  
  
  preds <- lapply(1:length(model.terms), function(i){
    pred <- lapply(models, function(m){
      mgcv::predict.gam(m, newd, exclude = model.terms[-i], type = "response")
      })
    
    pred <- as.data.frame(pred)
    colnames(pred) <- names(models)
    pred$x <- newd[[margin.terms[i]]]
    pred <- tidyr::pivot_longer(pred, cols = 1:length(models))
    return(pred)
  })
  names(preds) <- margin.terms
  return(preds)
  
}
```



## Plots

```{r  qq plot unfiltered}
pSeq <- seq(0, 0.1, by = 0.01)
df <- lapply(permResults$geneData$unfiltered, function(i){
  apply(i, 1, function(j){
    df <- as.data.frame(j)[!permResults$plotData$unfiltered$deMask,]
    df <- tidyr::replace_na(df, list(rep(1, 120)))
    df <- apply(df, 1, function(k){#
      sapply(pSeq, function(p) mean(k < p, na.rm = T))
    })
    rowMeans(df, na.rm = T)
  })
})
df <- as.data.frame(rbind(df[[1]], df[[2]]))
df$n <- rep(c(10,40), each = nrow(df)/2)
df$p <- pSeq
p1 <- tidyr::pivot_longer(df, 1:9) %>%
  ggplot(mapping = aes(x = p, y = value, col = name, linetype = name)) +
  geom_line() +
  geom_abline(intercept = 0, slope = 1) +
  facet_wrap(~n) 

p2 <- tidyr::pivot_longer(df, 1:9) %>%
  ggplot(mapping = aes(x = p, y = value/p, col = name, linetype = name)) +
  geom_line() +
  geom_abline(intercept = 0, slope = 0) +
  facet_wrap(~n)  +
  scale_y_log10()
p_all <- cowplot::plot_grid(p1, p2, nrow = 2)

file_name <- paste("../plots/", 
                   "qqPlotUnfiltered", ".png", 
                   sep = "")

cowplot::save_plot(p_all, filename = file_name, nrow =2)      
```

```{r  qq plot filtered}
pSeq <- seq(0, 0.1, by = 0.01)
df <- lapply(permResults$geneData$filtered, function(i){
  apply(i, 1, function(j){
    df <- as.data.frame(j)[!permResults$plotData$filtered$deMask,]
    df <- apply(df, 1, function(k){
      sapply(pSeq, function(p) mean(k < p, na.rm = T))
    })
    rowMeans(df, na.rm = T)
  })
})
df <- as.data.frame(rbind(df[[1]], df[[2]]))
df$n <- rep(c(10,40), each = nrow(df)/2)
df$p <- pSeq
p1 <- tidyr::pivot_longer(df, 1:9) %>%
  ggplot(mapping = aes(x = p, y = value, col = name, linetype = name)) +
  geom_line() +
  geom_abline(intercept = 0, slope = 1) +
  facet_wrap(~n) 

p2 <- tidyr::pivot_longer(df, 1:9) %>%
  ggplot(mapping = aes(x = p, y = value/p, col = name, linetype = name)) +
  geom_line() +
  geom_abline(intercept = 0, slope = 0) +
  facet_wrap(~n)  +
  scale_y_log10()
p_all <- cowplot::plot_grid(p1, p2, nrow = 2)

file_name <- paste("../plots/", 
                   "qqPlotFiltered", ".png", 
                   sep = "")

cowplot::save_plot(p_all, filename = file_name, nrow =2)      
```




```{r}
AlphaOptim <- function(alphaHat, alphaTarget, df){
  (mean(df < alphaHat, na.rm = T) - alphaTarget)^2
}


GetEmpAlpha <- function(data, alphaTarget){
  res <- list()
  ### Unfiltered Genes for n == 10
  res$unfiltered$"10" <- sapply(1:9, function(i){                                                      # for all 9 methods
    df <- as.data.frame(data$geneData$unfiltered$"10"[i,])               # Filter our NDe Genes
    df <- df[!permResults$plotData$unfiltered$deMask,]
    optimize(AlphaOptim, interval = c(0,1), alphaTarget = alphaTarget, df = as.matrix(df))[[1]]
  }
  )
  ### Unfiltered Genes for n == 40
  res$unfiltered$"40" <- sapply(1:9, function(i){                                                      # for all 9 methods
    df <- as.data.frame(data$geneData$unfiltered$"40"[i,])               # Filter our NDe Genes
    df <- df[!permResults$plotData$unfiltered$deMask,]
    optimize(AlphaOptim, interval = c(0,1), alphaTarget = alphaTarget, df = as.matrix(df))[[1]]
  }
  )
  ### Filtered Genes for n == 10
  res$filtered$"10" <- sapply(1:9, function(i){                                                      # for all 9 methods
    df <- as.data.frame(data$geneData$filtered$"10"[i,])               # Filter our NDe Genes
    df <- df[!permResults$plotData$filtered$deMask,]
    optimize(AlphaOptim, interval = c(0,1), alphaTarget = alphaTarget, df = as.matrix(df))[[1]]
  }
  )
  ###  Filtered Genes for n == 40
  res$filtered$"40" <- sapply(1:9, function(i){                                                      # for all 9 methods
    df <- as.data.frame(data$geneData$filtered$"40"[i,])               # Filter our NDe Genes
    df <- df[!permResults$plotData$filtered$deMask,]
    optimize(AlphaOptim, interval = c(0,1), alphaTarget = alphaTarget, df = as.matrix(df))[[1]]
  }
  )
  
  res
}

permResults$alphaAdjusted <- GetEmpAlpha(permResults, 0.05)
```

```{r}
permResults$
```

```{r}
a <- 0.05
### Know, get type-I error for all genes using both the nominal level,
### As well as the different adjusted alpha levels
t1Data <- list()
t1Data$nominal$unfiltered      <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                          GeneData = permResults$geneData$unfiltered, 
                                          alphas = rep(a, 12))

t1Data$adjusted$unfiltered     <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                            GeneData = permResults$geneData$unfiltered, 
                                            alphas = permResults$alphaAdjusted$unfiltered$"10")

t1DataAdjustedUnfiltered40   <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                          GeneData = permResults$geneData$unfiltered, 
                                          alphas = permResults$alphaAdjusted$unfiltered$"40")

### Replace the t1 Data such that it corresponds to the correct sample size
t1Data$adjusted$unfiltered$value[t1Data$adjusted$unfiltered$n == 40] <-
  t1DataAdjustedUnfiltered40$value[t1DataAdjustedUnfiltered40$n == 40]

### Repeat for filtered data
t1Data$nominal$filtered      <- GetT1Data(PlotData = permResults$plotData$filtered,
                                          GeneData = permResults$geneData$filtered, 
                                          alphas = rep(a, 12))

t1Data$adjusted$filtered     <- GetT1Data(PlotData = permResults$plotData$filtered,
                                            GeneData = permResults$geneData$filtered, 
                                            alphas = permResults$alphaAdjusted$filtered$"10")

t1DataAdjustedfiltered40   <- GetT1Data(PlotData = permResults$plotData$filtered,
                                          GeneData = permResults$geneData$filtered, 
                                          alphas = permResults$alphaAdjusted$filtered$"40")

### Replace the t1 Data such that it corresponds to the correct sample size
t1Data$adjusted$filtered$value[t1Data$adjusted$filtered$n == 40] <-
  t1DataAdjustedfiltered40$value[t1DataAdjustedfiltered40 $n == 40]

rm(t1DataAdjustedfiltered40, t1DataAdjustedUnfiltered40)




### For each of the Type-I errors, fit Generalized Additive Models (GAMs)
t1Models <- list()
t1Models$nominal$unfiltered  <- GetModels(t1Data$nominal$unfiltered,
                                        as.formula(value ~ s(log(mu)) + s(sqrt(phi)) + s(corrMax)))
t1Models$adjusted$unfiltered <- GetModels(t1Data$adjusted$unfiltered,
                                          as.formula(value ~ s(log(mu)) + s(sqrt(phi)) + s(corrMax)))

t1Models$nominal$filtered  <- GetModels(t1Data$nominal$filtered,
                                        as.formula(value ~ s(log(mu)) + s(sqrt(phi)) + s(corrMax)))
t1Models$adjusted$filtered <- GetModels(t1Data$adjusted$filtered,
                                        as.formula(value ~ s(log(mu)) + s(sqrt(phi)) + s(corrMax)))


### Now, compute cutoffs for which we want to plot the models,
### Use the predict function to obtain the actual curve
t1Preds <- list()
cutoffs <- as.data.frame(apply(permResults$plotData$unfiltered[,1:3], 2, quantile, c(0, 0.95)))
t1Preds$nominal$unfiltered  <- GetPreds(t1Models$nominal$unfiltered, cutoffs)
t1Preds$adjusted$unfiltered  <- GetPreds(t1Models$adjusted$unfiltered, cutoffs)

cutoffs <- as.data.frame(apply(permResults$plotData$filtered[,1:3], 2, quantile, c(0, 0.95)))
t1Preds$nominal$filtered  <- GetPreds(t1Models$nominal$filtered, cutoffs)
t1Preds$adjusted$filtered  <- GetPreds(t1Models$adjusted$filtered, cutoffs)
```


```{r}

```

```{r}
labelOrder <- row.names(permResults$geneData$unfiltered$"10")
title_name <- "Probability of Rejection under H_0"
p1 <- t1Data$nominal$unfiltered %>% 
  dplyr::filter(deMask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  geom_hline(yintercept = a) +
  scale_y_log10() +
  scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.4, 0.5, 1))

file_name <- paste("../plots/Unfiltered", 
                   gsub(" ", "_", title_name, fixed = T), ".png", 
                   sep = "")

ggsave(file_name, p1)

title_name <- "Probability of Rejection under H_0"
p1 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  geom_hline(yintercept = a) +
  scale_y_log10() +
  scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.4, 0.5, 1))

fileName <- paste("../plots/Filtered", 
                   gsub(" ", "_", title_name, fixed = T), ".png", 
                   sep = "")

ggsave(fileName, p1)
```


```{r}
### Power Boxplots
title_name <- "Probability of Rejection under H_A"
p1 <- t1Data$adjusted$unfiltered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  scale_y_log10() +
  scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.5, 1))

file_name <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "AdjustedUnfiltered.png", sep = "")

ggsave(file_name, p1)

title_name <- "Probability of Rejection under H_A"
p1 <- t1Data$adjusted$filtered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  scale_y_log10() +
  scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.5, 1))

file_name <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "Adjustedfiltered.png", sep = "")

ggsave(file_name, p1)
```

```{r}
### Power Boxplots of
title_name <- "Probability of Rejection under H_A"
p1 <- t1Data$nominal$unfiltered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  scale_y_log10() +
  scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.5, 1))

file_name <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "NominalUnfiltered.png", sep = "")

ggsave(file_name, p1)

title_name <- "Probability of Rejection under H_A"
p1 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  scale_y_log10() +
  scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.5, 1))

file_name <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "Nominalfiltered.png", sep = "")

ggsave(file_name, p1)
```


## Rankings

```{r}
title_name <- "Difference in Mean Ranks"

res <- lapply(PermResults$GeneData$Unfiltered, function(i){
  apply(i, 1, function(col){
    df <- as.data.frame(col)
    df <- apply(df, 2, rank)
    apply(df, 2, function(col) abs(mean(col[1:500]) - mean(col[501:1500])))
  })
})

res <- as.data.frame(rbind(res[[1]], res[[2]]))
res$n <- rep(c(10, 40), each = nrow(res)/2)
res <- pivot_longer(res, 1:9)

p1 <- ggplot(res, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~n)  +
  scale_x_discrete(guide = guide_axis(angle = 90))  +
  labs(y = "Difference in Meank Ranks", title = title_name)

file_name <- paste("../plots/PermUF", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```


## Lineplots for unfiltered genes

```{r}
GetPlots <- function(preds, modelnames, DE, title, ymax = 1){
  plot_list <- lapply(names(preds), function(var) {
    df <-preds[[var]] %>%
      tidyr::separate(col = name, into = c("Model", "n", "D"), sep = "_") %>%
      dplyr::filter((Model %in% modelnames) & D == DE)
    
    df %>%
      ggplot(mapping = aes(x = x, y= value, col = Model)) +
      geom_line() +
      geom_hline(yintercept = 0.01) +
      labs(x = var, y = "P(p <= 0.01)") +
      facet_wrap(~n) +
      scale_y_log10() +
      scale_y_continuous(breaks= c(0, 0.05, 0.1, 0.2, 0.5, 1), limits = c(0, ymax))
  })

  plot_list[[1]] <- plot_list[[1]] + labs(title = title) +
    theme(legend.position="none")
  plot_list[[3]] <- plot_list[[3]] + theme(legend.position="none")
  p_all <- cowplot::plot_grid(plot_list[[1]], plot_list[[2]], plot_list[[3]], nrow = 3,
                               align = "v", axis = "r")
  
  return(p_all)
}
```



```{r Plots for Parametric Methods under H0}
title_name <- "Parametric Methods under H0"
p_all <- GetPlots(t1Preds$nominal$unfiltered, labelOrder[1:4], DE = "NDE", title =  title_name, ymax = 0.5)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3)    

title_name <- "Parametric Methods under HA"
p_all <- GetPlots(t1Preds$adjusted$unfiltered, labelOrder[1:4], DE = "DE", title =  title_name)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3)  

title_name <- "Nonparametric Methods under H0"
p_all <- GetPlots(t1Preds$nominal$unfiltered, labelOrder[5:9], DE = "NDE", title =  title_name, ymax = 0.5)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3)

title_name <- "Nonparametric Methods under HA"
p_all <- GetPlots(t1Preds$adjusted$unfiltered, labelOrder[5:9], DE = "DE", title =  title_name)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3)

```


# Generation: H0 Setting with Large Sample Size

```{r}
sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))
glm.nb <- MASS::glm.nb
dataDir <- "../data/"

resFileName <- paste0(dataDir, "LIHCGenerationResultsH0.Rds")
tcgaData   <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))

DE_size <- 500
p_genes <- DE_size*5
```



```{r Get Parameters for Simulation}
randInt <- sample(nrow(tcgaData$counts), 10000)
#compute norm factors for permutations
d <- edgeR::DGEList(counts = tcgaData$counts[randInt,])
rownames(d) <-  1:nrow(d)

d <- edgeR::calcNormFactors(d)
d <- edgeR::estimateDisp(d)

#define parameters
phi <- d$tagwise.dispersion
mu <- rowMeans(d$counts*d$samples$norm.factors)
mu_1 <- mu_2 <-  mu[phi < 6][1:p_genes]
phi_1 <- phi_2 <- phi[phi < 6][1:p_genes]

#create differential expression
mu_2[1:(DE_size/2)] <- mu_2[1:(DE_size/2)]*2
mu_2[((DE_size/2)+1):DE_size] <- mu_2[((DE_size/2)+1):DE_size]/2
```


```{r}
GenResults <-list()
GenResults$plot_data <- data.frame(mu_1 = mu_1,
                        mu_2 = mu_2,
                        phi_1 = phi_1,
                        phi_2 = phi_2,
                        de_mask = 1:p_genes <= DE_size)

n_list <- list("10" = 10, "40" = 40, "200" = 200)
n_repl <- 2 #ca. 17:00
```


```{r}
t0 <- Sys.time()

suppressMessages(suppressWarnings(
  ### For Each Sample Size n:
  GenResults$GeneData <- lapply(n_list, function(n){
  print(n)
  ### Inner Loop: Replicate n_repl times
  replicate(n_repl,{
    XY_data <- Simulate_NB(n, p_genes, mu_1 = mu_1, mu_2 = mu_2, phi_1 = phi_1, phi_2 = phi_1)
    res <- list()
    print("Next it")
    res$EdgeR  <- EdgeRPipeline(XY_data$X, XY_data$Y)$p.value
    res$DESeq2 <- DESeq2Pipeline(XY_data$X, XY_data$Y)$p.value
    res$Limma  <- LimmaPipeline(XY_data$X, XY_data$Y)$p.value
    res$MW <- WilcoxPipeline(XY_data$X, XY_data$Y)$p.value
    res$DP <- DirectPermutationsPipeline(XY_data$X, XY_data$Y, n_flips = 200)$p.value
    res$FsP.B     = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "basic", n_flips = 200)$p.value
    res$FsP.E = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "effective", n_flips = 200)$p.value
    res$FsP.S  = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "standardized", n_flips = 200)$p.value
    return(res)
    })
  })
))

saveRDS(GenResults, file = ResFileName)
print(Sys.time() - t0)
```

```{r}
rm(mu_1, mu_2, phi_1, phi_2,  mask)
```


## Plotting

```{r}
library(ggplot2)
library(dplyr)
data.dir <- "../data/"
GenResults <- readRDS( file = ResFileName)
ResFileName <- paste0(data.dir, "LIHCGenerationResultsH0.Rds")
sapply(list.files("../R/"), function(f) source(paste0("../R/", f)))
```

```{r}
t1_data <- GetT1Data(GenResults, alpha = 0.005)
```


```{r}
t1_data %>% 
  dplyr::filter(t1_data$de_mask == F)
```

```{r}
title_name <- "Probability of Rejection under H_0"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(y = "P(p <= 0.05)", title = title_name) +
  geom_hline(yintercept = 0.005) +
  ylim(c(0, 0.05))

file_name <- paste("../plots/GenH0", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```


```{r}
title_name <- "Probability of Rejection under H_A"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(y = "P(p <= 0.005)", title = title_name)

file_name <- paste("../plots/GenH0", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```
# Generation Varying Phi by Group

```{r}
library(edgeR)
library(tidyr)
sapply(list.files("../R/"), function(f) source(paste0("../R/", f)))
glm.nb <- MASS::glm.nb
data.dir <- "../data/"

ResFileName <- paste0(data.dir, "LIHCGenerationResultsPhiDiff.Rds")
tcga_data <- readRDS(paste0(data.dir, "TCGA-LIHC_processed.RDs"))

DE_size <- 200
p_genes <- DE_size*3
```
```{r}
rand_int <- sample(nrow(tcga_data$counts), 5000)
#compute norm factors for permutations
d <- edgeR::DGEList(counts = tcga_data$counts[rand_int,], group = tcga_data$treatment)
rownames(d) <-  1:nrow(d)

d <- edgeR::calcNormFactors(d)
d <- edgeR::estimateDisp(d)

#define parameters
phi <- d$tagwise.dispersion
mu <- rowMeans(d$counts*d$samples$norm.factors)
mu_1 <- mu_2 <-  mu[phi < 5][1:p_genes]
phi_1 <- phi_2 <- phi[phi < 5][1:p_genes]

phi_1 <- phi_1*c(1, 1.5, 1.6)
phi_2 <- phi_2*c(1, 0.75, 0.4)

#create overdispersion
mu_2[1:(DE_size/2)] <- mu_2[1:(DE_size/2)]*2
mu_2[((DE_size/2)+1):DE_size] <- mu_2[((DE_size/2)+1):DE_size]/2

unique(phi_1/phi_2)
```



```{r}
GenResults <-list()
GenResults$plot_data <- data.frame(mu_1 = mu_1,
                        mu_2 = mu_2,
                        phi_1 = phi_1,
                        phi_2 = phi_2,
                        de_mask = 1:p_genes <= DE_size)

n_list <- list("10" = 10, "40" = 40)
n_repl <- 200 #ca. 17:00
```


```{r}
t0 <- Sys.time()

suppressMessages(suppressWarnings(
  ### For Each Sample Size n:
  GenResults$GeneData <- lapply(n_list, function(n){
  print(n)
  ### Inner Loop: Replicate n_repl times
  replicate(n_repl,{
    XY_data <- Simulate_NB(n, p_genes, mu_1 = mu_1, mu_2 = mu_2, phi_1 = phi_1, phi_2 = phi_1)
    res <- list()
    print("Next it")
    res$EdgeR  <- EdgeRPipeline(XY_data$X, XY_data$Y)$p.value
    res$DESeq2 <- DESeq2Pipeline(XY_data$X, XY_data$Y)$p.value
    res$Limma  <- LimmaPipeline(XY_data$X, XY_data$Y)$p.value
    res$MW <- WilcoxPipeline(XY_data$X, XY_data$Y)$p.value
    res$DP <- DirectPermutationsPipeline(XY_data$X, XY_data$Y, n_flips = 200)$p.value
    res$FsP.B     = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "basic", n_flips = 200)$p.value
    res$FsP.E = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "effective", n_flips = 200)$p.value
    res$FsP.S  = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "standardized", n_flips = 200)$p.value
    return(res)
    })
  })
))

saveRDS(GenResults, file = ResFileName)
print(Sys.time() - t0)
```

```{r}
rm(mu_1, mu_2, phi_1, phi_2,  mask)
```


## Plotting

```{r}
library(ggplot2)
library(dplyr)
data.dir <- "../data/"
ResFileName <- paste0(data.dir, "LIHCGenerationResultsPhiDiff.Rds")
GenResults <- readRDS(file = ResFileName)
sapply(list.files("../R/"), function(f) source(paste0("../R/", f)))
```

```{r}
t1_data <- GetT1Data(GenResults, alpha = 0.01)
```



```{r}
t1_data$phi_ratio <- round(t1_data$phi_1  / t1_data$phi_2,2)
t1_data
``` 

```{r}
t1_data %>% 
  dplyr::filter(t1_data$de_mask == F)
```

```{r}
title_name <- "Probability of Rejection under H_0"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(n ~phi_ratio) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(y = "P(p < 0.1)", title = title_name) +
  geom_hline(yintercept = 0.1)

file_name <- paste("../plots/GenPhiDiff", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```
```{r}
p1
```


```{r}
title_name <- "Probability of Rejection under H_A"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(n ~phi_ratio) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(y = "P(p < 0.1)", title = title_name) +
  geom_hline(yintercept = 0.1)

file_name <- paste("../plots/GenPhiDiff", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```
# Generation Varying phi

```{r}
library(edgeR)
library(tidyr)
sapply(list.files("../R/"), function(f) source(paste0("../R/", f)))
glm.nb <- MASS::glm.nb
data.dir <- "../data/"

ResFileName <- paste0(data.dir, "LIHCGenerationResultsPhi.Rds")
```

```{r}
tcga_data <- readRDS(paste0(data.dir, "TCGA-LIHC_processed.RDs"))
```



```{r}
rand_int <- sample(nrow(tcga_data$counts), 7000)
#compute norm factors for permutations
d <- edgeR::DGEList(counts = tcga_data$counts[rand_int,], group = tcga_data$treatment)
rownames(d) <-  1:nrow(d)
keep = edgeR::filterByExpr(d)
d = d[keep,,keep.lib.sizes=FALSE]
rm(keep)

d <- edgeR::calcNormFactors(d)
d <- edgeR::estimateDisp(d)

phi_1 <- sample(quantile(d$tagwise.dispersion), size = nrow(d), replace = T)
mu_1 <- rowMeans(d$counts*d$samples$norm.factors)


mu_mask  <- mu_1 < quantile(mu_1, c(0.99))
phi_mask <- phi_1 < quantile(phi_1, c(0.99))
mask <- mu_mask & phi_mask

DE_size <- 200
p_genes <- DE_size*3

phi_1 <- phi_1 <- rep(c(1e-10, 0.5, 1, 2), length.out = p_genes)
mu_1 <- mu_1[mask][1:p_genes]


phi_2 <- phi_1
mu_2 <- mu_1

mu_2[1:(DE_size/2)] <- mu_2[1:(DE_size/2)]*2
mu_2[((DE_size/2)+1):DE_size] <- mu_2[((DE_size/2)+1):DE_size]/2


mu <- (mu_1 + mu_2)/2
  
XY_data <- Simulate_NB(500, p_genes, mu_1 = mu_1, mu_2 = mu_2, phi_1 = phi_1, phi_2 = phi_2)
d <- DGEList(counts = XY_data$X, group = XY_data$Y)
d <- estimateDisp(d)

phi_plot <- d$tagwise.dispersion
mu_plot <- d$AveLogCPM

rm(tcga_data, XY_data, d, mu_mask)
```


```{r}
GenResults <-list()
GenResults$plot_data <- data.frame(mu_1 = mu_1,
                        mu_2 = mu_2,
                        phi_1 = phi_1,
                        phi_2 = phi_2,
                        de_mask = 1:p_genes <= DE_size)

n_list <- list("10" = 10, "40" = 40)
n_repl <- 50 #ca. 17:00
```


```{r}
t0 <- Sys.time()

suppressMessages(suppressWarnings(
  ### For Each Sample Size n:
  GenResults$GeneData <- lapply(n_list, function(n){
  print(n)
  ### Inner Loop: Replicate n_repl times
  replicate(n_repl,{
    XY_data <- Simulate_NB(n, p_genes, mu_1 = mu_1, mu_2 = mu_2, phi_1 = phi_1, phi_2 = phi_1)
    res <- list()
    print("Next it")
    res$EdgeR  <- EdgeRPipeline(XY_data$X, XY_data$Y)$p.value
    res$DESeq2 <- DESeq2Pipeline(XY_data$X, XY_data$Y)$p.value
    res$Limma  <- LimmaPipeline(XY_data$X, XY_data$Y)$p.value
    res$Wilcoxon <- WilcoxPipeline(XY_data$X, XY_data$Y)$p.value
    res$FSPoisson.Basic     = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "basic", n_flips = 500)$p.value
    res$FSPoisson.Effective = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "effective", n_flips = 500)$p.value
    res$FSPoisson.Standard  = FlipScoresPipeline(XY_data$X, XY_data$Y, "poisson", score_type = "standardized", n_flips = 500)$p.value
    return(res)
    })
  })
))

saveRDS(GenResults, file = ResFileName)
print(Sys.time() - t0)
```

```{r}
rm(mu_1, mu_2, phi_1, phi_2,  mask)
```


## Plotting

```{r}
library(ggplot2)
library(dplyr)
data.dir <- "../data/"
ResFileName <- paste0(data.dir, "LIHCGenerationResults.Rds")
GenResults <- readRDS( file = ResFileName)
sapply(list.files("../R/"), function(f) source(paste0("../R/", f)))
```

```{r}
t1_data <- GetT1Data(GenResults)
```

```{r}
t1_data
```

```{r}
t1_data$phi_ratio <- round(t1_data$phi_1  / t1_data$phi_2,2)
t1_data
``` 

```{r}
t1_data %>% 
  dplyr::filter(t1_data$de_mask == F)
```

```{r}
title_name <- "Probability of Rejection under H_0"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(n ~phi_1, nrow = 2) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(y = "P(p < 0.1)", title = title_name) +
  geom_hline(yintercept = 0.1)

file_name <- paste("../plots/Gen", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```
```{r}
p1
```


```{r}
title_name <- "Probability of Rejection under H_A"
p1 <- t1_data %>% 
  dplyr::filter(de_mask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(n ~phi_ratio) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  labs(y = "P(p < 0.1)", title = title_name) +
  geom_hline(yintercept = 0.1)

file_name <- paste("../plots/Gen", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1)
```

