---
title: "ETOC: Permutation Study"
output:
  html_document:
    toc: true
    theme: united
---


# Non-Parametric Permutation Study

## Permutation Study

```{r Setup}
set.seed(123)
library(dplyr)
library(MASS)
library(ggplot2)
library(tidyr)
library(cowplot)

### Load Helper Functions
sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))

### Load Data
dataDir <- "../data/"
tcgaData <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))

### Subset Data for two-group Comparison
tcgaDataCleaned <- tcgaData <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))
tcgaDataCleaned$counts <- tcgaData$counts[,!tcgaData$patientMaskDelete]
tcgaDataCleaned$group  <- tcgaData$group[!tcgaData$patientMaskDelete]

### Load p-values of all methods and convert to data frame
namesList <- names(tcgaData$Results)
LIHCRes <- as.data.frame(tcgaData$Results)
colnames(LIHCRes) <- namesList


### Rename Genes to Integers
rownames(tcgaDataCleaned$counts) <- 1:nrow(tcgaDataCleaned$counts)

### Load previous simulation results or create new list
resFileName <- paste0(dataDir, "LIHCPermutationResults.Rds")
if (file.exists(resFileName)){
  permResults <- readRDS(resFileName)
} else{
  permResults <- list()
}
```


```{r}
### Create Masks for Genes that are Differentially Expressed (De)  and
### Not Differentially Expressed (NDe)
LIHCResDE <- as.array(t(apply(LIHCRes, 1, p.adjust, method = "BH")) <= 0.005)
LIHCResNDe <- LIHCRes > 0.1
De <- rowSums(LIHCResDE, na.rm = T) >= 6
NDe <- rowSums(LIHCResNDe, na.rm = T) >= 6

### Get Random Selection of genes of a given size for a given ratio
DeSize <- 250
De  <- sample(which(De), DeSize)
NDe <- sample(which(NDe), DeSize*4)
YDe  <- tcgaDataCleaned$counts[De,]
YNDe <- tcgaDataCleaned$counts[NDe,]
YAll <- rbind(YDe, YNDe)
rownames(YAll) <- 1:nrow(YAll)
XAll <- tcgaDataCleaned$group == "Primary solid Tumor"   

### Compute norm factors and Dispersion on full dataset for later analyses
dAll <- edgeR::DGEList(counts = YAll, group = XAll)
dAll <- edgeR::calcNormFactors(dAll)
dAll <- edgeR::estimateDisp(dAll)

### Maximum Absolute Correlation for each gene
cAll <- abs(cor(t(edgeR::cpm(dAll))))
diag(cAll) <- 0
cMax <- apply(cAll, 2, max) 

### save plotting data
plotData <- data.frame(mu = rowMeans(dAll$counts * dAll$samples$norm.factors),
                        phi = dAll$tagwise.dispersion,
                        corrMax = cMax,
                        deMask = 1:nrow(dAll) <= DeSize)

rm(cMax, cAll)

### Set Simulation Parameters
nRepl <- 200
nList <- list("12" = 12,  "60" = 60)

permResults$plotData <- plotData
saveRDS(permResults, file = resFileName)

rm(plotData, tcgaData)
```


```{r Running Simulation w/o Filtering}
#ca. 18h
t0 <- Sys.time()    
### For Each Sample Size n:
permResults$geneData$unfiltered <- lapply(nList, function(n){
  print(n)
  c <- 0
  tN <- Sys.time()
  ### Inner Loop: Replicate n_repl times
  replicate(nRepl,{
    ### Print Progress and Increase Counter
    PrintProgress(c, nRepl, tN)
    c <<- c + 1
    XYData <- GetXYperm(n, YDe, YNDe, XAll, DESize, dAll$samples$norm.factors)
    res    <- RunAllMethods(XYData$Y, XYData$X)
  return(res)
  })
})

saveRDS(permResults, file = resFileName)
print(Sys.time() - t0)
```



```{r Running Simulation w Filtering}
nRepl <- 200
t0 <- Sys.time()   
### For Each Sample Size n:
permResults$geneData$filtered <- lapply(nList, function(n){
  print(n)
  c <- 0
  tN <- Sys.time()
  ### Inner Loop: Replicate n_repl times
  replicate(nRepl,{
    PrintProgress(c, nRepl, tN)
    c <<- c + 1
    XYData <- GetXYperm(n, YDe, YNDe, XAll, DESize, dAll$samples$norm.factors)
    rn <- rownames(XYData$Y)
    
    ### Filtering
    d <- edgeR::DGEList(counts = XYData$Y, group = XYData$X)
    d <- edgeR::calcNormFactors(d)
    keep = edgeR::filterByExpr(d)
    d <- d[keep,]
    XYData$Y <- d$counts
    
    res <- RunAllMethods(XYData$Y, XYData$X)
    
    df <- data.frame(row.names = rn, matrix(nrow = length(rn), ncol = 9))
    df[keep, ] <- as.data.frame(res)
    
    colnames(df) <- names(res)
    return(df)
    })
})

saveRDS(permResults, file = resFileName)
print(Sys.time() - t0)
```




# Creation of Plots



```{r}
dataDir <- "../data/"
tcgaData    <- readRDS(paste0(dataDir, "TCGALIHC.Rds"))
resFileName <- paste0(dataDir, "LIHCPermutationResults.Rds")
permResults <- readRDS(resFileName)
sapply(list.files("../functions/"), function(f) source(paste0("../functions/", f)))
```

```{r}
names(permResults$geneData$unfiltered)
```

```{r}
GetQQPlot <- function(data, deMask){
  ### Specify breaks of plot
  breaks <- c(0, 0.05, 0.1, 0.15, 0.2)  
  ### specify steps at which rejection rates should be computed
  pSeq <- seq(0, 0.2, by = 0.001)
  
  ### For each sample size in data
  df <- lapply(data, function(i){
    ### For each method in data of sample size
    apply(i, 1, function(j){
      ###construct df and replace NA's with 1 (not rejected)
      df <- as.data.frame(j)[!deMask,]
      df[is.na(df)] <- 1
      ###finally: loop through all replications, compute
      sapply(pSeq, function(p) mean(df < p, na.rm = T))
      })
    })
  ### Bind the two dataframes of the two sample sizes together
  df <- as.data.frame(rbind(df[[1]], df[[2]]))
  ### annotate data frame
  df$n <- rep(names(data), each = nrow(df)/2)
  df$p <- pSeq
  
  ### Get Legend
  legend <- tidyr::pivot_longer(df, 1:9) %>%
    ggplot(mapping = aes(x = p, y = value, col = name, linetype = name)) +
    geom_line() +
    facet_wrap(~n) +
    theme(legend.position = "bottom", legend.title = element_blank())
  legend <-cowplot::get_legend(legend)
  
  ### Plot qq-plots
  plotQQ <- tidyr::pivot_longer(df, 1:9) %>%
    ggplot(mapping = aes(x = p, y = value, col = name, linetype = name)) +
    geom_line() +
    geom_abline(intercept = 0, slope = 1) +
    facet_wrap(~n) +
    scale_x_continuous(breaks = breaks,
                       labels = as.character(breaks)) +
    labs(x = "Nominal Rejection Rate",
         y = "Observed Rejection Rate")  +
    theme(legend.position = "none", legend.title = element_blank())
  
  ### Plot factors
  plotFactors <- tidyr::pivot_longer(df, 1:9) %>%
    ggplot(mapping = aes(x = p, y = value/p, col = name, linetype = name)) +
    geom_line() +
    geom_abline(intercept = 0, slope = 0) +
    facet_wrap(~n)  +
    scale_y_log10(limits = c(1e-2, 1e2)) +
    scale_x_continuous(breaks = breaks,
                       labels = as.character(breaks)) +
    labs(x = "Nominal Rejection Rate",
         y = "Inflation Factor") +
    theme(legend.position = "none", legend.title = element_blank())
  
  pAll <- plot_grid(plot_grid(plotQQ, plotFactors, ncol = 2), legend, nrow = 2, rel_heights = c(1, 0.2))
  
  return(pAll)
}
```


```{r}
### Get QQ plots for Unfiltered Genes
fileName <- paste("../plots/", 
                   "qqPlotUnfiltered", ".png", 
                   sep = "")
pAll <- GetQQPlot(permResults$geneData$unfiltered, permResults$plotData$unfiltered$deMask)
cowplot::save_plot(pAll, filename = fileName, ncol =2, base_width = 3, base_height = 4)


### Get QQ plots for filtered Genes
fileName <- paste("../plots/", 
                   "qqPlotFiltered", ".png", 
                   sep = "")
pAll <- GetQQPlot(permResults$geneData$filtered, permResults$plotData$unfiltered$deMask)
cowplot::save_plot(pAll, filename = fileName, ncol =2, base_width = 3, base_height = 4)
```


```{r}
GetFDRPlot <- function(data, deMask){
  ### Loop through data w. different sample sizes
  fdr <- lapply(data, function(nDf){
    ### Loop through methods
    fdrDf <- sapply(1:9, function(i){
      
      ### for each method, apply BH for each replication (in columns)
      df <- as.data.frame(nDf[i,])
      df <- apply(df, 2, p.adjust, method = "BH") <= 0.05
      ### Compute FDP
      fdr <- 1 - colSums(df[deMask,], na.rm = T) / colSums(df, na.rm = T)
      names(fdr) <- NULL
      fdr
      })
    ### division by zero --> NA = 0
    fdrDf <- replace_na(fdrDf, 0)
    colnames(fdrDf) <- row.names(data$"12")
    fdrDf
  })
  ### bind results of different sample sizes together, append data for sample size
  fdr <- as.data.frame(rbind(fdr[[1]], fdr[[2]]))
  
  return(fdr)
  df$n <- rep(names(data), each = nrow(fdr)/2)
  
  ### extract label order (for plotting)
  labelOrder <- row.names(data$"12")
  
  ### plot fdr
  fdrPlot <- fdr %>% pivot_longer(cols = 1:9) %>%
    ggplot(mapping = aes(x = name, y = value)) +
    geom_boxplot() +
    facet_wrap(~n) +
    stat_summary(fun=mean, geom="point", shape=20, size=1, color="red", fill="red") +
    geom_hline(yintercept = 0.05, col = "gold") +
    scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
    labs(title = "Observed FDP of all Methods \n", y = "FDP", x = "Model Name")
  
  ### Repeat the same steps for the specificity
  nDe <- lapply(data, function(nDf){
    nDeDf <- sapply(1:9, function(i){
      df <- as.data.frame(nDf[i,])
      df <- apply(df, 2, p.adjust, method = "BH") <= 0.05
      nDe <- colSums(df[deMask,], na.rm = T) /
        sum(deMask)
      names(nDe) <- NULL
      nDe
      })
    colnames(nDeDf) <- row.names(data$"12")
    nDeDf
  })
  nDe <- as.data.frame(rbind(nDe[[1]], nDe[[2]]))
  nDe$n <- rep(names(data), each = nrow(nDe)/2)
  p2 <- nDe %>% pivot_longer(cols = 1:9) %>%
    ggplot(mapping = aes(x = name, y = value)) +
    geom_boxplot() +
    facet_wrap(~n) +
    scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder)+
    labs(title = "Observed Sensitivity \nof all Methods", y = "Sensitivity", x = "Model Name")
  
  pAll <- cowplot::plot_grid(p1, p2, ncol = 2)
  return(pAll)
  }
```


```{r FDR Unfiltered}
### Unfiltered
FDRPlotUnfiltered <- GetFDRPlot(data = permResults$geneData$unfiltered, 
                                deMask = permResults$plotData$unfiltered$deMask)
fileName <- paste("../plots/UnfilteredFDR", ".png", sep = "")
cowplot::save_plot(fileName, FDRPlotUnfiltered, ncol = 2, base_width = 3, base_height = 3.8)
```

```{r}
labelOrder
```


```{r}
df <- as.data.frame(permResults$geneData$filtered$"12"[1,])
df <- apply(df, 2, function(c){
  pValsNotFiltered <- p.adjust(c[!is.na(c)], method = "BH")
  pValsAll <- rep(NA, length(c))
  pValsAll[!is.na(c)] <- pValsNotFiltered
  pValsAll
})

df[,1]
```


```{r FDR Filtered}
### Filtered
fdr <- lapply(permResults$geneData$filtered, function(nDf){
  fdrDf <- sapply(1:9, function(i){
    df <- as.data.frame(nDf[i,])
    df <- apply(df, 2,  function(c){
      pValsNotFiltered <- p.adjust(c[!is.na(c)], method = "BH") <= 0.05
      pValsAll <- rep(NA, length(c))
      pValsAll[!is.na(c)] <- pValsNotFiltered
      pValsAll
    })
    fdr <- 1 - colSums(df[permResults$plotData$unfiltered$deMask,], na.rm = T) / colSums(df, na.rm = T)
    names(fdr) <- NULL
    fdr
  })
  fdrDf <- replace_na(fdrDf, 0)
  colnames(fdrDf) <- row.names(permResults$geneData$filtered$"12")
  fdrDf
})
fdr <- as.data.frame(rbind(fdr[[1]], fdr[[2]]))
fdr$n <- rep(names(permResults$geneData$filtered), each = nrow(fdr)/2)

labelOrder <- row.names(permResults$geneData$unfiltered$"12")

p1 <- fdr %>% pivot_longer(cols = 1:9) %>%
  ggplot(mapping = aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~n) +
  stat_summary(fun=mean, geom="point", shape=20, size=1, color="red", fill="red") +
  geom_hline(yintercept = 0.05, col = "gold") +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(title = "Observed FDP of all Methods \n", y = "FDP", x = "Model Name")


nDe <- lapply(permResults$geneData$filtered, function(nDf){
  nDeDf <- sapply(1:9, function(i){
    df <- as.data.frame(nDf[i,])
    df <- apply(df, 2, p.adjust, method = "BH") <= 0.05
    nDe <- colSums(df[permResults$plotData$unfiltered$deMask,], na.rm = T) / sum(permResults$plotData$unfiltered$deMask)
    names(nDe) <- NULL
    nDe
  })
  colnames(nDeDf) <- row.names(permResults$geneData$unfiltered$"12")
  nDeDf
})

nDe <- as.data.frame(rbind(nDe[[1]], nDe[[2]]))
nDe$n <- rep(c(10, 40), each = nrow(fdr)/2)

p2 <- nDe %>% pivot_longer(cols = 1:9) %>%
  ggplot(mapping = aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder)+
  labs(title = "Observed Sensitivity \nof all Methods", y = "Sensitivity", x = "Model Name")
  


pAll <- cowplot::plot_grid(p1, p2, ncol = 2)

fileName <- paste("../plots/FilteredFDR", ".png", sep = "")
ggsave(fileName, p1, width = 3.5, height = 4)

cowplot::save_plot(fileName, pAll, ncol = 2, base_width = 3, base_height = 3.8)
```

```{r}
a <- 0.01
permResults$alphaAdjusted <- GetEmpAlpha(permResults, 0.01)
### Know, get type-I error for all genes using both the nominal level,
### As well as the different adjusted alpha levels
t1Data <- list()
t1Data$nominal$unfiltered      <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                          GeneData = permResults$geneData$unfiltered, 
                                          alphas = rep(a, 12))

t1Data$adjusted$unfiltered     <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                            GeneData = permResults$geneData$unfiltered, 
                                            alphas = permResults$alphaAdjusted$unfiltered$"10")

t1DataAdjustedUnfiltered40   <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                          GeneData = permResults$geneData$unfiltered, 
                                          alphas = permResults$alphaAdjusted$unfiltered$"40")

### Replace the t1 Data such that it corresponds to the correct sample size
t1Data$adjusted$unfiltered$value[t1Data$adjusted$unfiltered$n == 40] <-
  t1DataAdjustedUnfiltered40$value[t1DataAdjustedUnfiltered40$n == 40]

### Repeat for filtered data
t1Data$nominal$filtered      <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                          GeneData = permResults$geneData$filtered, 
                                          alphas = rep(a, 12))

t1Data$adjusted$filtered     <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                            GeneData = permResults$geneData$filtered, 
                                            alphas = permResults$alphaAdjusted$filtered$"10")

t1DataAdjustedfiltered40   <- GetT1Data(PlotData = permResults$plotData$unfiltered,
                                          GeneData = permResults$geneData$filtered, 
                                          alphas = permResults$alphaAdjusted$filtered$"40")

### Replace the t1 Data such that it corresponds to the correct sample size
t1Data$adjusted$filtered$value[t1Data$adjusted$filtered$n == 40] <-
  t1DataAdjustedfiltered40$value[t1DataAdjustedfiltered40 $n == 40]

rm(t1DataAdjustedfiltered40, t1DataAdjustedUnfiltered40)
```


```{r Boxplots unfiltered}
labelOrder <- row.names(permResults$geneData$unfiltered$"12")
title_name <- "Probability of Rejection of \nNDE genes"
p1 <- t1Data$nominal$unfiltered %>% 
  dplyr::filter(deMask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=20, size=1, color="red", fill="red") +
  facet_wrap(n~., scales = "free") +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  geom_hline(yintercept = a) +
  scale_y_continuous(trans = "sqrt")


title_name <- "Probability of Rejection of \nDE genes"
p2 <- t1Data$nominal$unfiltered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  scale_y_continuous(trans = "sqrt")


pAll <- cowplot::plot_grid(p1, p2, ncol = 2)

fileName <- paste("../plots/UnfilteredT1", ".png", sep = "")

cowplot::save_plot(fileName, pAll, ncol = 2, base_width = 3.5, base_height = 4)
```

```{r Boxplots filtered}
labelOrder <- row.names(permResults$geneData$filtered$"12")
title_name <- "Probability of Rejection of\nNDE genes"
p1 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=20, size=1, color="red", fill="red") +
  facet_wrap(n~., scales = "free") +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  geom_hline(yintercept = a) +
  scale_y_continuous(trans = "sqrt")


title_name <- "Probability of Rejection of\nDE genes"
p2 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name, x = "Model Name") +
  scale_y_continuous(trans = "sqrt")


pAll <- cowplot::plot_grid(p1, p2, ncol = 2)

fileName <- paste("../plots/FilteredT1", ".png", sep = "")

cowplot::save_plot(fileName, pAll, ncol = 2, base_width = 3.5, base_height = 4)
```



```{r}
### Power Boxplots
title_name <- "Probability of Rejection under H_0"
p2 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == F) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  geom_hline(yintercept = a) +
  scale_y_continuous(limits = c(0, 1))

title_name <- "Probability of Rejection under H_A"
p4 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.05)", title = title_name) +
  scale_y_continuous(limits = c(0, 1))

fileName <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "Adjustedfiltered.png", sep = "")

ggsave(fileName, p1, width = 4, height = 5)
```

```{r}
### Power Boxplots of
title_name <- "Probability of Rejection under H_A"
p1 <- t1Data$nominal$unfiltered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  scale_y_continuous(limits = c(0, 1))

fileName <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "NominalUnfiltered.png", sep = "")

ggsave(fileName, p1, width = 4, height = 5)

titleName <- "Probability of Rejection under H_A"
p1 <- t1Data$nominal$filtered %>% 
  dplyr::filter(deMask == T) %>%
  ggplot(aes(x = name, y = value)) +
  geom_boxplot()+
  facet_wrap(~n) +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "P(p <= 0.01)", title = title_name) +
  scale_y_continuous(limits = c(0, 1))

file_name <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), "Nominalfiltered.png", sep = "")

ggsave(fileName, p1, width = 4, height = 5)
```

```{r Rankings Unfiltered}
title_name <- "Difference in Mean Ranks"
res <- lapply(permResults$geneData$unfiltered, function(i){
  apply(i, 1, function(col){
    df <- as.data.frame(col)
    df <- apply(df, 2, rank)
    apply(df, 2, function(col) abs(mean(col[permResults$plotData$unfiltered$deMask]) - mean(col[!permResults$plotData$unfiltered$deMask])))
  })
})

res <- as.data.frame(rbind(res[[1]], res[[2]]))
res$n <- rep(c(12, 60), each = nrow(res)/2)
res <- pivot_longer(res, 1:9)

p1 <- ggplot(res, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~n)  +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "Difference in Meank Ranks", title = title_name, x = "Model Name")

file_name <- paste("../plots/PermUnfiltered", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1, width = 3, height = 3.8)
```


```{r Rankings Filtered}
title_name <- "Difference in Mean Ranks"
res <- lapply(permResults$geneData$filtered, function(i){
  apply(i, 1, function(col){
    df <- as.data.frame(col)
    df <- apply(df, 2, rank, na.last = T)
    apply(df, 2, function(col) abs(mean(col[permResults$plotData$unfiltered$deMask], na.rm = T) -
                                     mean(col[!permResults$plotData$unfiltered$deMask])))
  })
})

res <- as.data.frame(rbind(res[[1]], res[[2]]))
res$n <- rep(c(12, 60), each = nrow(res)/2)
res <- pivot_longer(res, 1:9)

p1 <- ggplot(res, aes(x = name, y = value)) +
  geom_boxplot() +
  facet_wrap(~n)  +
  scale_x_discrete(guide = guide_axis(angle = 90), limits = labelOrder) +
  labs(y = "Difference in Meank Ranks", title = title_name, x = "Model Name")

file_name <- paste("../plots/PermFiltered", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")

ggsave(file_name, p1, width = 3, height = 3.8)
```



## Lineplots for unfiltered genes

```{r}
### For each of the Type-I errors, fit Generalized Additive Models (GAMs)
t1Models <- list()
t1Models$nominal$unfiltered  <- GetModels(t1Data$nominal$unfiltered,
                                        as.formula(value ~ s(sqrt(mu)) + s(sqrt(phi)) + s(corrMax)))
t1Models$adjusted$unfiltered <- GetModels(t1Data$adjusted$unfiltered,
                                          as.formula(value ~ s(sqrt(mu)) + s(sqrt(phi)) + s(corrMax)))

#t1Models$nominal$filtered  <- GetModels(t1Data$nominal$filtered,
#                                        as.formula(value ~ s(log(mu)) + s(sqrt(phi)) + s(corrMax)))
#t1Models$adjusted$filtered <- GetModels(t1Data$adjusted$filtered,
#                                        as.formula(value ~ s(log(mu)) + s(sqrt(phi)) + s(corrMax)))


### Now, compute cutoffs for which we want to plot the models,
### Use the predict function to obtain the actual curve
t1Preds <- list()
cutoffs <- as.data.frame(apply(permResults$plotData$unfiltered[,1:3], 2, quantile, c(0, 0.95)))
t1Preds$nominal$unfiltered  <- GetPreds(t1Models$nominal$unfiltered, cutoffs)
t1Preds$adjusted$unfiltered  <- GetPreds(t1Models$adjusted$unfiltered, cutoffs)

#t1Preds$nominal$filtered  <- GetPreds(t1Models$nominal$filtered, cutoffs)
#t1Preds$adjusted$filtered  <- GetPreds(t1Models$adjusted$filtered, cutoffs)
```


```{r Plots for Parametric Methods under H0}
title_name <- "Parametric Methods under H0 without Filtering"
p_all <- GetLinePlots(t1Preds$nominal$unfiltered, labelOrder[1:4], DE = "NDE", title =  title_name, ymax = 0.8)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3, base_width = 7, base_height = 3)    

title_name <- "Parametric Methods under HA without Filtering"
p_all <- GetLinePlots(t1Preds$nominal$unfiltered, labelOrder[1:4], DE = "DE", title =  title_name, ymax = 1)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3, base_width = 7, base_height = 3)  

title_name <- "Nonparametric Methods under H0 without Filtering"
p_all <- GetLinePlots(t1Preds$nominal$unfiltered, labelOrder[5:9], DE = "NDE", title =  title_name, ymax = 0.25)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3, base_width = 7, base_height = 3)    

title_name <- "Nonparametric Methods under HA without Filtering"
p_all <- GetLinePlots(t1Preds$nominal$unfiltered, labelOrder[5:9], DE = "DE", title =  title_name, ymax = 1)
file_name_H0 <- paste("../plots/Perm", gsub(" ", "_", title_name, fixed = T), ".png", sep = "")
cowplot::save_plot(p_all, filename = file_name_H0, nrow =3, base_width = 7, base_height = 3)    

```




